name: Run Docling OCR

on:
  push:
    paths:
      - "orders/**"  # trigger when you add or change PDFs

jobs:
  ocr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install docling

      - name: Run OCR pipeline
        run: python ocr_script.py

      - name: Commit OCR results
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add outputs/
          git commit -m "Add OCR outputs"
          git push
